version: "3"

services:
  app:
    image: forecast_api_image
    container_name: forecast_api_container
    build:
      context: .
    volumes:
      - .:/app
    ports:
      - 5000:5000
    env_file: 
      - .env
    restart: always